dirs:
  - content/en/
ignorePatterns:
  - pattern: '^https://twitter.com
  - pattern: '^http://localhost'
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
replacementPatterns:
  - pattern: "^/"
    replacement: "${{ steps.pages.outputs.base_url }}/"