dirs:
  - content/en/
ignorePatterns:
  - pattern: '^https://twitter.com'
  - pattern: '^http://localhost'
  - pattern: '^https://www.biorxiv.org/content/'
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
replacementPatterns:
  - pattern: "^/"
    replacement: "https://neurodesk.org/"
  - pattern: "^https://github.com/NeuroDesk/(.*?)/blob/main/(.*)"
    replacement: "https://api.github.com/repos/NeuroDesk/$1/contents/$2"
httpHeaders:
  - url:
      - https://api.github.com
    headers:
      Authorization: Bearer ${GITHUB_TOKEN}
      Accept: application/vnd.github+json