dirs:
  - content/en/
ignorePatterns:
  - pattern: '^https://twitter.com'
  - pattern: '^http://localhost'
  - pattern: '^https://www.biorxiv.org/content/'
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
replacementPatterns:
  - pattern: "^/"
    replacement: "https://neurodesk.org/"