dirs:
  - content/en/
ignorePatterns:
  - pattern: '^https://twitter.com'
  - pattern: '^http://localhost'
  - pattern: '^https://www.biorxiv.org/content/'
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
replacementPatterns:
  - pattern: "^/"
    replacement: "https://neurodesk.org/"
httpHeaders:
  - url:
      - https://github.com
    headers:
      Authorization: ${{ secrets.GITHUB_TOKEN }}
excludedFiles:
- 'content/en/developers/contributors/_index.md'