name: github pages

on:
  push:
    branches: ["main"]
  repository_dispatch:
  workflow_dispatch:
#  schedule: ## Run at 12.am daily to check for broken links automatically
 #   - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      HUGO_VERSION: 0.139.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Install dependencies
        run: | 
          npm install

      - name: Write applist.json
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        run: |
          if [ -n "$ZENODO_TOKEN" ]; then
            python .github/workflows/write-app-json.py --zenodo_token "$ZENODO_TOKEN"
          else
            echo "ZENODO_TOKEN not set — skipping write-app-json.py"
          fi
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          if [[ "${{ github.repository }}" == "neurodesk/neurodesk.github.io" ]]; then
            echo "Building for production domain: https://www.neurodesk.org/"
            hugo \
              --minify \
              --baseURL "https://www.neurodesk.org/"
          else
            # Temporary fix for css paths in forks
            sed -i "s|canonifyURLs=true|canonifyURLs=false|g" config.toml
            sed -i "s|/static/|/neurodesk.github.io/static/|g" content/en/_index.md
            sed -i "s|/static/|/neurodesk.github.io/static/|g" content/en/docs/Getting\ Started/Local/neurodeskapp.md
            sed -i "s|/static/|/neurodesk.github.io/static/|g" content/en/docs/Overview/acknowledgement.md
            sed -i "s|/static/|/neurodesk.github.io/static/|g" content/en/docs/Overview/metrics.md
            # Construct the base URL for forks
            BASE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
            echo "Building for fork/preview domain: ${BASE_URL}"
            hugo \
              --minify \
              --baseURL "${BASE_URL}"
          fi

      - name: Add custom domain
        if: github.repository == 'neurodesk/neurodesk.github.io'
        run: cp ./static/CNAME ./public/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

  check-links:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector with reviewdog
        uses: UmbrellaDocs/action-linkspector@v1.3.6  
        with:
          fail_on_error: true
          reporter: github-pr-review
          config_file: .linkspector.yml
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          show_stats: true
          level: info

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Algolia crawler creation and crawl
      #   uses: algolia/algoliasearch-crawler-github-actions@v1.1.9
      #   id: algolia_crawler
      #   with: # mandatory parameters
      #     crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
      #     crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
      #     algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
      #     algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
      #     site-url: 'https://www.neurodesk.org'
